### ISSUE TITLE
Ensure that you are using an AVR target!

### ISSUE THREAD

**Issue by eflukx** [Rahix/avr-hal-template#3]
Installed template as documented (for Arduino Uno), builds fine, no problems! 

But rust-analyzer doesn't really like it and chokes on _Ensure that you are using an AVR target!_

![image](https://user-images.githubusercontent.com/996191/141537927-bab9f8bb-5b9d-4bfa-8002-a58d8b69bcc4.png)

**Comment by Rahix** [comment]
Hm, probably means that rust-analyzer attempts building for your host architecture instead of AVR?  Does it not pick up the `.cargo/config.toml` file?  In there, you should have a

```toml
[build]
target = "avr-something"
```

section to tell cargo to automatically build for AVR.

**Comment by eflukx** [comment]
I'm using the template unchanged (configured for Arduino Uno), my `config.toml` reads

```toml
[build]
target = "avr-specs/avr-atmega328p.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno -cb 57600"

[unstable]
build-std = ["core"]
```

Any avr-hal or arduino-hal example I tried, gave me the same issue with rust analyzer somehow...  

_As a sidenote: when I was looking for the correct avr-arch-triplet, I found that running `rustup target list' does not include any AVR target. (This is probably normal for AVR, needing a custom targetr spec .json file...)_
